---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-cpi-release
run:
  path: bosh-cpi-release/ci/tasks/reset-resources.sh
params:
  AZURE_TENANT_ID:               replace-me
  AZURE_CLIENT_ID:               replace-me
  AZURE_CLIENT_SECRET:           replace-me
  AZURE_GROUP_NAME_FOR_VMS:      replace-me
  AZURE_GROUP_NAME_FOR_NETWORK:  replace-me
  AZURE_STORAGE_ACCOUNT_NAME:    replace-me
  AZURE_VNET_NAME_FOR_BATS:      replace-me
  AZURE_VNET_NAME_FOR_LIFECYCLE: replace-me
  AZURE_BOSH_SUBNET_NAME:        replace-me
  AZURE_CF_SUBNET_NAME:          replace-me
