---
platform: linux
image: docker:///sedouard/azure-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: setup-director
run:
  path: bosh-cpi-release/ci/tasks/teardown-director.sh
params:
  BOSH_INIT_LOG_LEVEL:        warn